### ISSUE TITLE
Assets cannot be displayed after migration is complete

### ISSUE THREAD

**Issue by tuminfei** [uni-arts-chain/uniarts-eth-dao-frontend#6]
https://rinkeby.etherscan.io/tx/0x60aeb488a03fe29edf00577fdb42a33b9728cf760c8d02f9a6cf5373f8a97106

![image](https://user-images.githubusercontent.com/275027/140864432-416c7fc4-7a64-4e01-b682-f1e3a7ad0eec.png)

![image](https://user-images.githubusercontent.com/275027/140864389-e7d7bad0-96dc-4572-b6eb-d8b4591560e8.png)

**Comment by tuminfei** [comment]
应该是新用户无法显示资产的问题

**Comment by tianxiemaochiyu** [comment]
Done
